const https = require('https');
const fs = require('fs');
const path = require('path');

const COURSE_TITLE = process.env.COURSE_TITLE || 'مافیای استوری اینستاگرام';
const COURSE_PRICE = process.env.COURSE_PRICE || 'قیمت تستی';
const PAYMENT_URL = process.env.PAYMENT_URL || '';
const ADMIN_USERNAME = (process.env.ADMIN_USERNAME || 'Senpaizuto').replace(/^@/, '').toLowerCase();
const token = process.env.BOT_TOKEN;

if (!token) {
  console.log('[telegram] BOT_TOKEN is not set; Telegram bot is disabled.');
  module.exports = null;
} else {
  const API = `https://api.telegram.org/bot${token}`;
  const storageDir = path.join(__dirname, 'storage');
  const stateFile = path.join(storageDir, 'telegram-bot-state.json');
  let offset = 0, stopped = false;
  let ownerId = process.env.ADMIN_CHAT_ID ? String(process.env.ADMIN_CHAT_ID) : null;
  let receiptsEnabled = true, botEnabled = true, waitingForLink = null;
  const waitingForUserId = new Set(), waitingForSupport = new Set();
  const waitingForAdminReply = new Map(), waitingForUserReply = new Map();
  const waitingForManager = new Map(), waitingForOwnership = new Map();
  const pendingReceipts = new Map(), users = new Map(), supportTickets = new Map(), managers = new Map();
  const offlineQueue = [];
  const sleep = ms => new Promise(r => setTimeout(r, ms));
  const safe = s => String(s ?? '').replace(/[&<>]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));
  const displayName = u => [u?.first_name, u?.last_name].filter(Boolean).join(' ') || 'بدون نام';
  const displayUsername = u => u?.username ? `@${u.username}` : 'ندارد';
  const defaultPerms = () => ({receipts:true,support:true,users:true,settings:false,stats:true,managers:false,ownership:false});
  const isOwner = u => Boolean(ownerId && String(u?.id) === String(ownerId));
  const isManager = u => managers.has(String(u?.id));
  const hasPerm = (u,p) => isOwner(u) || Boolean(managers.get(String(u?.id))?.permissions?.[p]);
  const canAdmin = u => isOwner(u) || isManager(u);

  function loadState(){try{if(!fs.existsSync(stateFile))return;const s=JSON.parse(fs.readFileSync(stateFile,'utf8'));offset=Number(s.offset||0);ownerId=s.ownerId||ownerId;receiptsEnabled=s.receiptsEnabled!==false;botEnabled=s.botEnabled!==false;waitingForLink=s.waitingForLink||null;for(const x of s.users||[])users.set(String(x.userId),x);for(const x of s.pendingReceipts||[])pendingReceipts.set(String(x.id),x);for(const x of s.supportTickets||[])supportTickets.set(String(x.id),x);for(const x of s.managers||[])managers.set(String(x.userId),x);}catch(e){console.error('[telegram] state load failed:',e.message);}}
  function saveState(){try{fs.mkdirSync(storageDir,{recursive:true});const data={offset,ownerId,receiptsEnabled,botEnabled,waitingForLink,users:[...users.values()],pendingReceipts:[...pendingReceipts.values()],supportTickets:[...supportTickets.values()],managers:[...managers.values()]};const tmp=`${stateFile}.tmp`;fs.writeFileSync(tmp,JSON.stringify(data,null,2));fs.renameSync(tmp,stateFile);}catch(e){console.error('[telegram] state save failed:',e.message);}}
  function telegram(method,body={}){return new Promise((resolve,reject)=>{const url=new URL(`${API}/${method}`),payload=JSON.stringify(body);const req=https.request({hostname:url.hostname,port:443,path:url.pathname,method:'POST',family:4,headers:{'content-type':'application/json','content-length':Buffer.byteLength(payload)},timeout:35000},res=>{let data='';res.setEncoding('utf8');res.on('data',c=>data+=c);res.on('end',()=>{try{const p=JSON.parse(data);if(!p.ok)return reject(new Error(p.description||`Telegram API error: ${method}`));resolve(p.result);}catch{reject(new Error(`Invalid Telegram response (${res.statusCode})`));}})});req.on('timeout',()=>req.destroy(new Error('Telegram request timed out')));req.on('error',reject);req.write(payload);req.end();});}
  const send=(chatId,text,extra={})=>telegram('sendMessage',{chat_id:chatId,text,parse_mode:'HTML',...extra});
  const edit=(chatId,messageId,text,reply_markup)=>telegram('editMessageText',{chat_id:chatId,message_id:messageId,text,parse_mode:'HTML',reply_markup});
  const sendPhoto=(chatId,photo,caption,extra={})=>telegram('sendPhoto',{chat_id:chatId,photo,caption,parse_mode:'HTML',...extra});
  const sendDocument=(chatId,document,caption,extra={})=>telegram('sendDocument',{chat_id:chatId,document,caption,parse_mode:'HTML',...extra});
  const copyMessage=(chatId,fromChatId,messageId,extra={})=>telegram('copyMessage',{chat_id:chatId,from_chat_id:fromChatId,message_id:messageId,...extra});

  const mainKeyboard=()=>({inline_keyboard:[[{text:'🎓 معرفی دوره',callback_data:'course'}],[{text:'📚 سرفصل‌ها',callback_data:'syllabus'},{text:'🎁 نمونه رایگان',callback_data:'sample'}],[{text:'💰 خرید دوره',callback_data:'buy'}],[{text:'💬 پشتیبانی',callback_data:'support'}]]});
  const mainBack=()=>({inline_keyboard:[[{text:'↩️ برگشت به منوی اصلی',callback_data:'menu'}]]});
  const adminHome=()=>({inline_keyboard:[[{text:'🧾 رسیدها',callback_data:'admin_receipts'},{text:'💬 پشتیبانی',callback_data:'admin_support'}],[{text:'👥 کاربران',callback_data:'admin_users'},{text:'⚙️ تنظیمات',callback_data:'admin_settings'}],[{text:'📊 آمار',callback_data:'admin_stats'},{text:'🛡 مدیران',callback_data:'admin_managers'}],[{text:'👑 مالکیت بات',callback_data:'admin_ownership'}]]});
  const adminBack=()=>({inline_keyboard:[[{text:'↩️ پنل مدیر',callback_data:'admin_home'}]]});
  const adminReceipts=()=>({inline_keyboard:[[{text:'📥 رسیدهای جدید',callback_data:'pending_receipts'}],[{text:receiptsEnabled?'🟢 دریافت رسید: روشن':'🔴 دریافت رسید: خاموش',callback_data:'toggle_receipts'}],[{text:'↩️ پنل مدیر',callback_data:'admin_home'}]]});
  const adminSupport=()=>({inline_keyboard:[[{text:'📨 تیکت‌های باز',callback_data:'support_list'}],[{text:'↩️ پنل مدیر',callback_data:'admin_home'}]]});
  const adminUsers=()=>({inline_keyboard:[[{text:'🔎 جستجوی کاربر با ID',callback_data:'user_lookup'}],[{text:'↩️ پنل مدیر',callback_data:'admin_home'}]]});
  const adminSettings=()=>({inline_keyboard:[[{text:botEnabled?'🟢 بات: روشن':'🔴 بات: خاموش',callback_data:'toggle_bot'}],[{text:'📥 صف اختلال',callback_data:'queue_status'}],[{text:'↩️ پنل مدیر',callback_data:'admin_home'}]]});
  const adminStats=()=>({inline_keyboard:[[{text:'🔄 بروزرسانی',callback_data:'admin_stats'}],[{text:'↩️ پنل مدیر',callback_data:'admin_home'}]]});
  const adminManagers=()=>({inline_keyboard:[[{text:'➕ افزودن مدیر',callback_data:'manager_add'}],[{text:'📋 لیست مدیران',callback_data:'manager_list'}],[{text:'↩️ پنل مدیر',callback_data:'admin_home'}]]});
  const adminOwnership=()=>({inline_keyboard:[[{text:'👑 انتقال مالکیت',callback_data:'transfer_owner'}],[{text:'🆔 مالک فعلی',callback_data:'owner_info'}],[{text:'↩️ پنل مدیر',callback_data:'admin_home'}]]});
  const managerKeyboard=id=>({inline_keyboard:[[{text:'🛡 تنظیم دسترسی‌ها',callback_data:`manager_perms:${id}`}],[{text:'🗑 حذف مدیر',callback_data:`manager_remove:${id}`}],[{text:'↩️ مدیران',callback_data:'admin_managers'}]]});
  const receiptKeyboard=id=>({inline_keyboard:[[{text:'👤 اطلاعات کاربر',callback_data:`info:${id}`}],[{text:'✅ تایید',callback_data:`approve:${id}`},{text:'❌ رد',callback_data:`reject:${id}`}],[{text:'🔗 ارسال دسترسی',callback_data:`link:${id}`}],[{text:'↩️ رسیدها',callback_data:'admin_receipts'}]]});
  const userKeyboard=id=>({inline_keyboard:[[{text:'👤 اطلاعات',callback_data:`user_info:${id}`}],[{text:'🟢 اعطای دسترسی',callback_data:`grant:${id}`},{text:'🔴 لغو',callback_data:`revoke:${id}`}],[{text:'📥 رسیدها',callback_data:`user_receipts:${id}`}],[{text:'🔗 ارسال دسترسی',callback_data:`user_link:${id}`}],[{text:'↩️ کاربران',callback_data:'admin_users'}]]});
  const supportAdminKeyboard=id=>({inline_keyboard:[[{text:'↩️ پاسخ به این پیام',callback_data:`support_reply:${id}`}],[{text:'💬 پشتیبانی',callback_data:'admin_support'}]]});
  const supportUserKeyboard=id=>({inline_keyboard:[[{text:'↩️ پاسخ به پشتیبانی',callback_data:`support_user_reply:${id}`}],[{text:'🏠 منوی اصلی',callback_data:'menu'}]]});

  function getOrCreateUser(m){const id=String(m.from?.id||m.chat.id);let u=users.get(id);if(!u)u={userId:id,chatId:String(m.chat.id),name:displayName(m.from),username:m.from?.username||'',access:false,approved:false,rejected:false,createdAt:new Date().toISOString()};else{u.chatId=String(m.chat.id);u.name=displayName(m.from);u.username=m.from?.username||u.username||'';}users.set(id,u);saveState();return u;}
  function receiptParts(id){const m=String(id||'').match(/^(-?\d+):(\d+)$/);return m?{chatId:m[1],messageId:Number(m[2])}:null;}
  function getReceipt(id){const e=pendingReceipts.get(String(id));if(e)return e;const p=receiptParts(id);if(!p)return null;const r={id:String(id),chatId:p.chatId,userId:p.chatId,name:'کاربر رسید',username:'',approved:false,rejected:false,access:false,linkSent:'',fileType:'',fileId:''};pendingReceipts.set(String(id),r);users.set(String(r.userId),r);saveState();return r;}
  function messageSummary(m){if(m.text)return safe(m.text);if(m.caption)return safe(m.caption);if(m.photo)return '🖼️ عکس';if(m.video)return '🎥 ویدیو';if(m.document)return '📎 فایل';if(m.voice)return '🎤 پیام صوتی';if(m.audio)return '🎵 صوت';if(m.sticker)return '🙂 استیکر';return '📨 پیام';}
  function newTicketId(userId){return `${userId}-${Date.now()}`;}
  async function deliverSupportAdmin(t,m,reply=false){const recipients=[...(ownerId?[ownerId]:[]),...managers.values().filter(x=>x.permissions?.support).map(x=>x.userId)];if(!recipients.length)return;const text=`<b>${reply?'🔁 پاسخ جدید کاربر':'💬 پیام جدید پشتیبانی'}</b>\n\n👤 ${safe(displayName(m.from))}\n🔹 ${safe(displayUsername(m.from))}\n🆔 Telegram ID: <code>${safe(t.userId)}</code>\n🎫 تیکت: <code>${safe(t.id)}</code>\n\n${messageSummary(m)}\n\n<i>برای پاسخ، دکمه زیر را بزنید.</i>`;const extra={reply_markup:supportAdminKeyboard(t.id)};for(const recipient of [...new Set(recipients)]){try{if(m.photo)await sendPhoto(recipient,m.photo[m.photo.length-1].file_id,text,extra);else if(m.document)await sendDocument(recipient,m.document.file_id,text,extra);else if(m.video||m.voice||m.audio||m.sticker)await copyMessage(recipient,m.chat.id,m.message_id,extra);else await send(recipient,text,extra);}catch(e){console.error('[telegram] support delivery:',e.message);}}}
  async function createSupportTicket(m,idValue=null){const u=getOrCreateUser(m);let t=idValue?supportTickets.get(String(idValue)):null;if(!t)t={id:newTicketId(u.userId),userId:u.userId,chatId:String(m.chat.id),name:u.name,username:u.username,status:'open',createdAt:new Date().toISOString(),lastUserMessageId:m.message_id,lastAdminMessageId:null,lastMessageSummary:messageSummary(m),messages:[]};else{t.status='open';t.lastUserMessageId=m.message_id;t.lastMessageSummary=messageSummary(m);t.name=u.name;t.username=u.username;t.chatId=String(m.chat.id);}t.messages=t.messages||[];t.messages.push({from:'user',messageId:m.message_id,summary:messageSummary(m),at:new Date().toISOString()});supportTickets.set(t.id,t);saveState();await deliverSupportAdmin(t,m,Boolean(idValue));return t;}
  async function sendAdminReply(t,m){const u=users.get(String(t.userId)),chatId=t.chatId||u?.chatId||t.userId,extra={reply_markup:supportUserKeyboard(t.id)},cap=`<b>👑 پاسخ پشتیبانی</b>\n\n🎫 تیکت: <code>${safe(t.id)}</code>\n↩️ پاسخ به آخرین پیام شما`;if(m.photo)await sendPhoto(chatId,m.photo[m.photo.length-1].file_id,cap,extra);else if(m.document)await sendDocument(chatId,m.document.file_id,cap,extra);else if(m.video||m.voice||m.audio||m.sticker)await copyMessage(chatId,m.chat.id,m.message_id,extra);else await send(chatId,`${cap}\n\n${safe(m.text||m.caption||'پیام جدید از پشتیبانی')}`,extra);t.lastAdminMessageId=m.message_id;t.lastAdminSummary=m.text||m.caption||'پیام پشتیبانی';t.status='waiting_user';t.messages=t.messages||[];t.messages.push({from:'admin',messageId:m.message_id,summary:t.lastAdminSummary,at:new Date().toISOString()});saveState();}
  async function sendSupportList(chatId){const list=[...supportTickets.values()].filter(t=>t.status!=='closed');if(!list.length)return send(chatId,'📭 هیچ تیکت بازی وجود ندارد.',{reply_markup:adminSupport()});return send(chatId,`<b>💬 تیکت‌های باز</b>\n\nتعداد: <b>${list.length}</b>`,{reply_markup:{inline_keyboard:[...list.slice(0,30).map(t=>[{text:`🎫 ${t.id.slice(-12)} | ${String(t.name||'کاربر').slice(0,18)}`,callback_data:`support_reply:${t.id}`}]),[{text:'↩️ پشتیبانی',callback_data:'admin_support'}]]}});}
  async function sendPending(chatId){const list=[...pendingReceipts.values()].filter(r=>!r.approved&&!r.rejected);if(!list.length)return send(chatId,'📭 هیچ رسید تاییدنشده‌ای وجود ندارد.',{reply_markup:adminReceipts()});await send(chatId,`<b>📥 رسیدهای جدید</b>\n\nتعداد: <b>${list.length}</b>`,{reply_markup:adminReceipts()});for(const r of list){const text=`<b>📄 رسید پرداخت</b>\n\n🎓 ${safe(COURSE_TITLE)}\n💰 ${safe(COURSE_PRICE)}\n👤 ${safe(r.name)}\n🔹 ${safe(r.username?'@'+r.username:'ندارد')}\n🆔 <code>${safe(r.userId)}</code>`;const extra={reply_markup:receiptKeyboard(r.id)};if(r.fileType==='photo'&&r.fileId)await sendPhoto(chatId,r.fileId,text,extra);else if(r.fileType==='document'&&r.fileId)await sendDocument(chatId,r.fileId,text,extra);else await send(chatId,text,extra);}}
  async function showUser(chatId,id){const u=users.get(String(id));if(!u)return send(chatId,'⚠️ کاربر پیدا نشد.',{reply_markup:adminUsers()});return send(chatId,`<b>👤 مدیریت کاربر</b>\n\nنام: ${safe(u.name)}\nیوزرنیم: ${safe(u.username?'@'+u.username:'ندارد')}\n🆔 Telegram ID: <code>${safe(u.userId)}</code>\n💳 دسترسی: ${u.access?'🟢 دارد':'🔴 ندارد'}\n🧾 پرداخت: ${u.approved?'✅ تایید':u.rejected?'❌ رد':'⏳ تایید نشده'}`,{reply_markup:userKeyboard(u.userId)});}
  async function showManager(chatId,id){const x=managers.get(String(id));if(!x)return send(chatId,'⚠️ مدیر پیدا نشد.',{reply_markup:adminManagers()});return send(chatId,`<b>🛡 مدیر</b>\n\n🆔 <code>${safe(x.userId)}</code>\n👤 ${safe(x.name||'بدون نام')}\n🔹 ${safe(x.username?'@'+x.username:'ندارد')}`,{reply_markup:managerKeyboard(x.userId)});}
  function permissionKeyboard(id){const x=managers.get(String(id));if(!x)return adminManagers();const p=x.permissions||defaultPerms();const row=(key,label)=>({text:`${p[key]?'🟢':'🔴'} ${label}`,callback_data:`perm:${id}:${key}`});return {inline_keyboard:[[row('receipts','رسیدها'),row('support','پشتیبانی')],[row('users','کاربران'),row('settings','تنظیمات')],[row('stats','آمار'),row('managers','مدیران')],[row('ownership','مالکیت')],[{text:'↩️ مدیران',callback_data:'admin_managers'}]]};}
  async function sendManagerList(chatId){const list=[...managers.values()];if(!list.length)return send(chatId,'📭 هیچ مدیر دیگری ثبت نشده است.',{reply_markup:adminManagers()});return send(chatId,`<b>🛡 مدیران</b>\n\nتعداد: <b>${list.length}</b>`,{reply_markup:{inline_keyboard:[...list.map(x=>[{text:`👤 ${String(x.name||x.userId).slice(0,24)}`,callback_data:`manager_view:${x.userId}`}]),[{text:'↩️ مدیران',callback_data:'admin_managers'}]]}});}
  async function processOffline(){if(!botEnabled||!offlineQueue.length)return;const q=offlineQueue.splice(0);for(const x of q){try{if(x.type==='message'&&!x.admin){await send(x.chatId,'⚠️ به دلیل اختلال موقت، درخواست شما با تأخیر پردازش شد. بات دوباره فعال شده و درخواست شما در حال پردازش است.');await handleMessage(x.message,true);}else if(x.type==='callback')await handleCallback(x.callback,true);}catch(e){console.error('[telegram] queued:',e.message);}}}

  async function handleMessage(m,queued=false){
    const chatId=String(m.chat.id),text=String(m.text||'').trim(),admin=canAdmin(m.from),owner=isOwner(m.from);
    if(!botEnabled&&!admin&&!queued){offlineQueue.push({type:'message',chatId,message:m,admin:false});saveState();return;}
    if(admin){
      if(owner)ownerId=chatId;
      if(waitingForLink){const u=users.get(String(waitingForLink))||getReceipt(waitingForLink);if(!u){waitingForLink=null;saveState();return send(chatId,'⚠️ کاربر پیدا نشد.',{reply_markup:adminHome()});}if(!u.approved&&!u.access)return send(chatId,'⚠️ اول رسید را تایید کنید.',{reply_markup:adminHome()});try{await copyMessage(u.chatId,chatId,m.message_id);u.access=true;u.linkSent=text||'[پیام ارسال‌شده]';waitingForLink=null;saveState();return send(chatId,'✅ پیام برای کاربر ارسال شد و دسترسی فعال شد.',{reply_markup:adminHome()});}catch(e){return send(chatId,'❌ ارسال انجام نشد: '+safe(e.message),{reply_markup:adminHome()});}}
      if(waitingForAdminReply.has(chatId)){const id=waitingForAdminReply.get(chatId);waitingForAdminReply.delete(chatId);const t=supportTickets.get(id);if(!t)return send(chatId,'⚠️ تیکت پیدا نشد.',{reply_markup:adminSupport()});try{await sendAdminReply(t,m);return send(chatId,'✅ پاسخ برای کاربر ارسال شد.',{reply_markup:adminSupport()});}catch(e){return send(chatId,'❌ ارسال پاسخ ناموفق بود: '+safe(e.message),{reply_markup:adminSupport()});}}
      if(waitingForManager.has(chatId)&&/^\d+$/.test(text)&&hasPerm(m.from,'managers')){const id=text;waitingForManager.delete(chatId);if(String(id)===String(ownerId))return send(chatId,'⚠️ مالک فعلی نیازی به مدیر شدن ندارد.',{reply_markup:adminManagers()});const existing=managers.get(id)||{userId:id,permissions:defaultPerms()};existing.userId=id;existing.name=existing.name||'مدیر';managers.set(id,existing);saveState();return send(chatId,'✅ مدیر اضافه شد. حالا می‌توانید دسترسی‌های او را تنظیم کنید.',{reply_markup:managerKeyboard(id)});}
      if(waitingForOwnership.has(chatId)&&/^\d+$/.test(text)&&owner){const newOwner=text;waitingForOwnership.delete(chatId);if(newOwner===ownerId)return send(chatId,'⚠️ این کاربر همین حالا مالک است.',{reply_markup:adminOwnership()});const u=users.get(newOwner)||{userId:newOwner,chatId:newOwner,name:'مالک جدید',username:''};ownerId=newOwner;managers.delete(newOwner);users.set(newOwner,u);saveState();try{await send(newOwner,'👑 شما به عنوان مالک جدید بات تعیین شدید. اکنون دسترسی کامل به پنل مدیریت دارید.');}catch{}return send(chatId,'✅ مالکیت داخلی بات منتقل شد. شما دیگر مالک اصلی نیستید.',{reply_markup:adminHome()});}
      if(waitingForUserId.has(chatId)&&/^\d+$/.test(text)&&hasPerm(m.from,'users')){waitingForUserId.delete(chatId);return showUser(chatId,text);}
    }
    if(text==='/start'||text==='/menu')return send(chatId,`<b>🎓 ${safe(COURSE_TITLE)}</b>\n\nآموزش کاربردی ساخت و مدیریت استوری اینستاگرام.\n\n💰 ${safe(COURSE_PRICE)}\n\nاز منوی زیر انتخاب کنید 👇`,{reply_markup:mainKeyboard()});
    if(text==='/id')return send(chatId,`🆔 Telegram ID شما:\n<code>${safe(chatId)}</code>`);
    if(text==='/admin')return admin?send(chatId,'<b>👑 پنل مدیریت</b>\n\nیک بخش را انتخاب کنید 👇',{reply_markup:adminHome()}):send(chatId,'⛔ این دستور فقط برای مدیر است.');
    if(waitingForUserReply.has(chatId)){const id=waitingForUserReply.get(chatId);waitingForUserReply.delete(chatId);const t=supportTickets.get(id);if(!t)return send(chatId,'⚠️ تیکت پیدا نشد.',{reply_markup:mainKeyboard()});await createSupportTicket(m,id);return send(chatId,`✅ پیام شما برای پشتیبانی ارسال شد.\n\n🎫 تیکت: <code>${safe(id)}</code>\n↩️ این پیام پاسخ به آخرین پیام مدیر است.`,{reply_markup:mainBack()});}
    if(waitingForSupport.has(chatId)){waitingForSupport.delete(chatId);const t=await createSupportTicket(m);return send(chatId,`✅ پیام با موفقیت ارسال شد.\n\n🎫 شماره تیکت: <code>${safe(t.id)}</code>\n\nمنتظر پاسخ مدیران باشید.`,{reply_markup:mainBack()});}
    if(m.photo||m.document){if(!receiptsEnabled)return send(chatId,'🔴 دریافت رسید فعلاً خاموش است.',{reply_markup:mainKeyboard()});if(!ownerId&&!managers.size)return send(chatId,'📤 رسید دریافت شد؛ مدیر هنوز تنظیم نشده است.',{reply_markup:mainKeyboard()});const id=`${chatId}:${m.message_id}`,u=getOrCreateUser(m),r={...u,id,chatId,userId:String(m.from?.id||chatId),fileType:m.photo?'photo':'document',fileId:m.photo?m.photo[m.photo.length-1].file_id:m.document?.file_id||'',approved:false,rejected:false,access:false};pendingReceipts.set(id,r);users.set(r.userId,r);saveState();const cap=`<b>📥 رسید پرداخت جدید</b>\n\n🎓 ${safe(COURSE_TITLE)}\n💰 ${safe(COURSE_PRICE)}\n👤 ${safe(u.name)}\n🔹 ${safe(u.username?'@'+u.username:'ندارد')}\n🆔 <code>${safe(u.userId)}</code>`,extra={reply_markup:receiptKeyboard(id)},recipients=[...(ownerId?[ownerId]:[]),...managers.values().filter(x=>x.permissions?.receipts).map(x=>x.userId)];for(const recipient of [...new Set(recipients)]){try{if(m.photo)await sendPhoto(recipient,r.fileId,cap,extra);else await sendDocument(recipient,r.fileId,cap,extra);}catch(e){console.error('[telegram] receipt delivery:',e.message);}}return send(chatId,'📤 رسید دریافت شد و برای مدیر ارسال شد.',{reply_markup:mainKeyboard()});}
    return send(chatId,'از منوی زیر یک گزینه را انتخاب کنید 👇',{reply_markup:mainKeyboard()});
  }

  async function handleCallback(q,queued=false){
    const chatId=String(q.message.chat.id),action=String(q.data||''),from=q.from;try{await telegram('answerCallbackQuery',{callback_query_id:q.id});}catch{}if(!botEnabled&&!canAdmin(from)&&!queued){offlineQueue.push({type:'callback',callback:q});saveState();return;}
    const page=(text,markup)=>edit(chatId,q.message.message_id,text,markup);
    if(action==='course')return page(`<b>🎓 معرفی دوره</b>\n\nدوره <b>${safe(COURSE_TITLE)}</b> برای آموزش ساخت، ایده‌پردازی و مدیریت استوری‌های حرفه‌ای اینستاگرام.\n\n💰 ${safe(COURSE_PRICE)}`,mainBack());
    if(action==='syllabus')return page('<b>📚 سرفصل‌ها</b>\n\n1️⃣ اصول طراحی استوری\n2️⃣ ایده‌پردازی و سناریونویسی\n3️⃣ ساخت استوری جذاب\n4️⃣ افزایش تعامل\n5️⃣ فروش و برندینگ',mainBack());
    if(action==='sample')return page('<b>🎁 نمونه رایگان</b>\n\nنمونه رایگان دوره در این بخش قرار می‌گیرد.',mainBack());
    if(action==='buy')return page(`<b>💳 خرید دوره</b>\n\n🎓 ${safe(COURSE_TITLE)}\n💰 ${safe(COURSE_PRICE)}\n\nبعد از پرداخت، رسید را از گزینه زیر ارسال کنید.`,{inline_keyboard:[...(PAYMENT_URL?[[{text:'💳 پرداخت',url:PAYMENT_URL}]]:[]),[{text:'📤 ارسال رسید',callback_data:'send_receipt'}],[{text:'↩️ برگشت',callback_data:'menu'}]]});
    if(action==='send_receipt')return page('<b>📤 ارسال رسید</b>\n\nتصویر یا فایل رسید پرداخت را همینجا ارسال کنید.\n\nبعد از ارسال، رسید برای مدیر فرستاده می‌شود.',mainBack());
    if(action==='support'){waitingForSupport.add(chatId);return page('<b>💬 پشتیبانی</b>\n\nپیامی که می‌خواهید به پشتیبانی بگویید را همینجا ارسال کنید.\n\nمی‌توانید متن، عکس یا فایل بفرستید.',mainBack());}
    if(action.startsWith('support_user_reply:')){const id=action.slice(19),t=supportTickets.get(id);if(!t)return page('⚠️ تیکت پیدا نشد.',mainBack());waitingForUserReply.set(chatId,id);return page(`<b>↩️ پاسخ به پشتیبانی</b>\n\n🎫 تیکت: <code>${safe(id)}</code>\n\nپیام خود را ارسال کنید.`,mainBack());}
    if(action==='menu')return page(`<b>🎓 ${safe(COURSE_TITLE)}</b>\n\n💰 ${safe(COURSE_PRICE)}\n\nاز منوی زیر انتخاب کنید 👇`,mainKeyboard());
    if(!canAdmin(from))return send(chatId,'⛔ این بخش فقط برای مدیران است.');
    if(action==='admin_home')return page('<b>👑 پنل مدیریت</b>\n\nبخش موردنظر را انتخاب کنید 👇',adminHome());
    if(action==='admin_receipts'){if(!hasPerm(from,'receipts'))return page('⛔ دسترسی به رسیدها ندارید.',adminHome());return page('<b>🧾 مدیریت رسیدها</b>\n\nرسیدهای پرداخت را مدیریت کنید.',adminReceipts());}
    if(action==='pending_receipts'){if(!hasPerm(from,'receipts'))return page('⛔ دسترسی ندارید.',adminHome());await sendPending(chatId);return;}
    if(action==='toggle_receipts'){if(!hasPerm(from,'receipts'))return page('⛔ دسترسی ندارید.',adminHome());receiptsEnabled=!receiptsEnabled;saveState();return page(`<b>🧾 مدیریت رسیدها</b>\n\nدریافت رسید: ${receiptsEnabled?'🟢 روشن':'🔴 خاموش'}`,adminReceipts());}
    if(action==='admin_support'){if(!hasPerm(from,'support'))return page('⛔ دسترسی به پشتیبانی ندارید.',adminHome());return page('<b>💬 مدیریت پشتیبانی</b>\n\nتیکت‌های کاربران را مدیریت کنید.',adminSupport());}
    if(action==='support_list'){if(!hasPerm(from,'support'))return page('⛔ دسترسی ندارید.',adminHome());await sendSupportList(chatId);return;}
    if(action.startsWith('support_reply:')){if(!hasPerm(from,'support'))return send(chatId,'⛔ دسترسی ندارید.');const id=action.slice(14),t=supportTickets.get(id);if(!t)return send(chatId,'⚠️ تیکت پیدا نشد.',{reply_markup:adminSupport()});waitingForAdminReply.set(chatId,id);return send(chatId,`<b>↩️ پاسخ به تیکت</b>\n\n🎫 <code>${safe(id)}</code>\n🆔 <code>${safe(t.userId)}</code>\n\nپیام پاسخ را ارسال کنید. هر نوع پیام قابل ارسال است.`,{reply_markup:adminSupport()});}
    if(action==='admin_users'){if(!hasPerm(from,'users'))return page('⛔ دسترسی به کاربران ندارید.',adminHome());return page('<b>👥 مدیریت کاربران</b>\n\nکاربر را با Telegram ID پیدا کنید.',adminUsers());}
    if(action==='user_lookup'){if(!hasPerm(from,'users'))return send(chatId,'⛔ دسترسی ندارید.');waitingForUserId.add(chatId);return send(chatId,'🆔 Telegram ID کاربر را ارسال کنید.',{reply_markup:adminUsers()});}
    if(action.startsWith('user_info:'))return hasPerm(from,'users')?showUser(chatId,action.slice(10)):send(chatId,'⛔ دسترسی ندارید.');
    if(action.startsWith('grant:')){if(!hasPerm(from,'users'))return send(chatId,'⛔ دسترسی ندارید.');const u=users.get(action.slice(6));if(!u)return send(chatId,'⚠️ کاربر پیدا نشد.',{reply_markup:adminUsers()});u.access=true;saveState();return send(chatId,'🟢 دسترسی فعال شد.',{reply_markup:userKeyboard(u.userId)});}
    if(action.startsWith('revoke:')){if(!hasPerm(from,'users'))return send(chatId,'⛔ دسترسی ندارید.');const u=users.get(action.slice(7));if(!u)return send(chatId,'⚠️ کاربر پیدا نشد.',{reply_markup:adminUsers()});u.access=false;saveState();return send(chatId,'🔴 دسترسی لغو شد.',{reply_markup:userKeyboard(u.userId)});}
    if(action.startsWith('user_receipts:')){if(!hasPerm(from,'users'))return send(chatId,'⛔ دسترسی ندارید.');const id=action.slice(14),list=[...pendingReceipts.values()].filter(r=>String(r.userId)===String(id));if(!list.length)return send(chatId,'📭 رسیدی برای این کاربر ثبت نشده است.',{reply_markup:userKeyboard(id)});for(const r of list)await send(chatId,`🎫 رسید <code>${safe(r.id)}</code>\nوضعیت: ${r.approved?'✅ تایید':r.rejected?'❌ رد':'⏳ در انتظار'}`,{reply_markup:receiptKeyboard(r.id)});return;}
    if(action.startsWith('user_link:')){if(!hasPerm(from,'users'))return send(chatId,'⛔ دسترسی ندارید.');const id=action.slice(10),u=users.get(id);if(!u)return send(chatId,'⚠️ کاربر پیدا نشد.',{reply_markup:adminUsers()});if(!u.approved&&!u.access)return send(chatId,'⚠️ اول رسید کاربر را تایید کنید.',{reply_markup:adminUsers()});waitingForLink=id;saveState();return send(chatId,`📨 پیام بعدی شما برای کاربر <code>${safe(id)}</code> ارسال می‌شود.`,{reply_markup:adminUsers()});}
    if(action==='admin_settings'){if(!hasPerm(from,'settings'))return page('⛔ دسترسی به تنظیمات ندارید.',adminHome());return page('<b>⚙️ تنظیمات بات</b>\n\nوضعیت عملکرد بات و صف اختلال.',adminSettings());}
    if(action==='toggle_bot'){if(!hasPerm(from,'settings'))return page('⛔ دسترسی ندارید.',adminHome());botEnabled=!botEnabled;saveState();if(botEnabled){await page('<b>⚙️ تنظیمات بات</b>\n\n🟢 بات فعال شد.\n\nدرخواست‌های ذخیره‌شده در حال پردازش هستند...',adminSettings());await processOffline();}else return page('<b>⚙️ تنظیمات بات</b>\n\n🔴 بات خاموش شد.\n\nدرخواست‌های کاربران ذخیره می‌شوند تا بعداً پردازش شوند.',adminSettings());return;}
    if(action==='queue_status')return page(`<b>📥 صف اختلال</b>\n\nتعداد درخواست‌های ذخیره‌شده: <b>${offlineQueue.length}</b>`,adminSettings());
    if(action==='admin_stats'){if(!hasPerm(from,'stats'))return page('⛔ دسترسی ندارید.',adminHome());return page(`<b>📊 آمار و وضعیت</b>\n\n👥 کاربران: <b>${users.size}</b>\n🧾 رسیدها: <b>${pendingReceipts.size}</b>\n💬 تیکت‌ها: <b>${supportTickets.size}</b>\n🛡 مدیران: <b>${managers.size}</b>\n📥 صف اختلال: <b>${offlineQueue.length}</b>\n\nبات: ${botEnabled?'🟢 روشن':'🔴 خاموش'}\nرسید: ${receiptsEnabled?'🟢 روشن':'🔴 خاموش'}`,adminStats());}
    if(action==='admin_managers'){if(!hasPerm(from,'managers'))return page('⛔ فقط مالک یا مدیر دارای دسترسی مدیریت مدیران می‌تواند این بخش را ببیند.',adminHome());return page('<b>🛡 مدیریت مدیران</b>\n\nمدیران بات را اضافه و سطح دسترسی آن‌ها را تنظیم کنید.',adminManagers());}
    if(action==='manager_add'){if(!hasPerm(from,'managers'))return send(chatId,'⛔ دسترسی ندارید.');waitingForManager.set(chatId,true);return send(chatId,'🆔 Telegram ID مدیر جدید را ارسال کنید.',{reply_markup:adminManagers()});}
    if(action==='manager_list'){if(!hasPerm(from,'managers'))return send(chatId,'⛔ دسترسی ندارید.');await sendManagerList(chatId);return;}
    if(action.startsWith('manager_view:'))return hasPerm(from,'managers')?showManager(chatId,action.slice(13)):send(chatId,'⛔ دسترسی ندارید.');
    if(action.startsWith('manager_perms:')){if(!hasPerm(from,'managers'))return send(chatId,'⛔ دسترسی ندارید.');const id=action.slice(14);return page('<b>🛡 سطح دسترسی مدیر</b>\n\n🟢 فعال | 🔴 غیرفعال\n\nبرای تغییر روی دسترسی بزنید.',permissionKeyboard(id));}
    if(action.startsWith('perm:')){if(!hasPerm(from,'managers'))return send(chatId,'⛔ دسترسی ندارید.');const [,id,key]=action.split(':');const x=managers.get(id);if(!x)return send(chatId,'⚠️ مدیر پیدا نشد.',{reply_markup:adminManagers()});x.permissions=x.permissions||defaultPerms();if(key==='ownership'&&!isOwner(from))return send(chatId,'⛔ انتقال مالکیت فقط توسط مالک فعلی انجام می‌شود.',{reply_markup:permissionKeyboard(id)});x.permissions[key]=!x.permissions[key];saveState();return page('<b>🛡 سطح دسترسی مدیر</b>\n\nدسترسی‌ها به‌روزرسانی شد.',permissionKeyboard(id));}
    if(action.startsWith('manager_remove:')){if(!hasPerm(from,'managers'))return send(chatId,'⛔ دسترسی ندارید.');const id=action.slice(15);managers.delete(id);saveState();return page('✅ مدیر حذف شد.',adminManagers());}
    if(action==='admin_ownership'){if(!hasPerm(from,'ownership'))return page('⛔ فقط مالک یا مدیر دارای دسترسی مالکیت می‌تواند این بخش را ببیند.',adminHome());return page('<b>👑 مالکیت بات</b>\n\nانتقال مالکیت داخلی بات را مدیریت کنید.\n\n⚠️ فقط مالک فعلی می‌تواند مالکیت را منتقل کند.',adminOwnership());}
    if(action==='owner_info')return page(`<b>👑 مالک فعلی</b>\n\n🆔 <code>${safe(ownerId||'تنظیم نشده')}</code>`,adminOwnership());
    if(action==='transfer_owner'){if(!isOwner(from))return page('⛔ انتقال مالکیت فقط توسط مالک فعلی انجام می‌شود.',adminOwnership());waitingForOwnership.set(chatId,true);return send(chatId,'🆔 Telegram ID مالک جدید را ارسال کنید.\n\nپس از انتقال، مالک جدید دسترسی کامل خواهد داشت.',{reply_markup:adminOwnership()});}
    if(action.startsWith('info:')){if(!hasPerm(from,'receipts'))return send(chatId,'⛔ دسترسی ندارید.');const r=getReceipt(action.slice(5));if(!r)return send(chatId,'⚠️ رسید پیدا نشد.',{reply_markup:adminReceipts()});return send(chatId,`<b>👤 اطلاعات کاربر</b>\n\nنام: ${safe(r.name)}\nیوزرنیم: ${safe(r.username?'@'+r.username:'ندارد')}\n🆔 <code>${safe(r.userId)}</code>\nرسید: ${r.approved?'✅ تایید':r.rejected?'❌ رد':'⏳ در انتظار'}\nدسترسی: ${r.access?'🟢 دارد':'🔴 ندارد'}`,{reply_markup:receiptKeyboard(r.id)});}
    if(action.startsWith('approve:')){if(!hasPerm(from,'receipts'))return send(chatId,'⛔ دسترسی ندارید.');const r=getReceipt(action.slice(8));if(!r)return send(chatId,'⚠️ رسید پیدا نشد.',{reply_markup:adminReceipts()});r.approved=true;r.rejected=false;r.access=false;const u=users.get(String(r.userId));if(u){u.approved=true;u.rejected=false;}saveState();try{await send(r.chatId,'<b>✅ رسید شما تایید شد.</b>\n\nمدیر آماده ارسال دسترسی است.');}catch{}return send(chatId,'✅ رسید تایید شد. برای ارسال دسترسی «🔗 ارسال دسترسی» را بزنید.',{reply_markup:receiptKeyboard(r.id)});}
    if(action.startsWith('reject:')){if(!hasPerm(from,'receipts'))return send(chatId,'⛔ دسترسی ندارید.');const r=getReceipt(action.slice(7));if(!r)return send(chatId,'⚠️ رسید پیدا نشد.',{reply_markup:adminReceipts()});r.rejected=true;r.approved=false;r.access=false;const u=users.get(String(r.userId));if(u){u.approved=false;u.rejected=true;}saveState();try{await send(r.chatId,'❌ رسید پرداخت شما رد شد. در صورت اشتباه، رسید صحیح را دوباره ارسال کنید.');}catch{}return send(chatId,'❌ رسید رد شد.',{reply_markup:adminReceipts()});}
    if(action.startsWith('link:')){if(!hasPerm(from,'receipts'))return send(chatId,'⛔ دسترسی ندارید.');const r=getReceipt(action.slice(5));if(!r)return send(chatId,'⚠️ رسید پیدا نشد.',{reply_markup:adminReceipts()});if(!r.approved)return send(chatId,'⚠️ اول رسید را تایید کنید.',{reply_markup:receiptKeyboard(r.id)});waitingForLink=String(r.userId);saveState();return send(chatId,`📨 پیام بعدی شما برای کاربر <code>${safe(r.userId)}</code> ارسال می‌شود.`,{reply_markup:receiptKeyboard(r.id)});}
    return page('<b>👑 پنل مدیریت</b>\n\nیک بخش را انتخاب کنید 👇',adminHome());
  }

  async function poll(){while(!stopped){try{const updates=await telegram('getUpdates',{offset,timeout:25,allowed_updates:['message','callback_query']});for(const u of updates){offset=u.update_id+1;saveState();try{if(u.callback_query)await handleCallback(u.callback_query);else if(u.message)await handleMessage(u.message);}catch(e){console.error('[telegram] update error:',e.message);}}}catch(e){console.error('[telegram] polling error:',e.message);await sleep(3000);}}}
  async function startup(){loadState();try{await telegram('deleteWebhook',{drop_pending_updates:false});}catch(e){console.error('[telegram] deleteWebhook:',e.message);}try{const me=await telegram('getMe');console.log(`[telegram] bot connected: @${me.username||me.first_name}`);}catch(e){console.error('[telegram] getMe failed:',e.message);}await sleep(2000);if(botEnabled)await processOffline();poll();}
  process.once('SIGTERM',()=>{stopped=true;saveState();});process.once('SIGINT',()=>{stopped=true;saveState();});startup();module.exports={telegram};
}
