const https = require('https');
const fs = require('fs');
const path = require('path');

const COURSE_TITLE = process.env.COURSE_TITLE || 'مافیای استوری اینستاگرام';
const COURSE_PRICE = process.env.COURSE_PRICE || 'قیمت تستی';
const PAYMENT_URL = process.env.PAYMENT_URL || '';
const ADMIN_USERNAME = (process.env.ADMIN_USERNAME || 'Senpaizuto').replace(/^@/, '').toLowerCase();
const token = process.env.BOT_TOKEN;

if (!token) {
  console.log('[telegram] BOT_TOKEN is not set; Telegram bot is disabled.');
  module.exports = null;
} else {
  const API = `https://api.telegram.org/bot${token}`;
  const storageDir = path.join(__dirname, 'storage');
  const stateFile = path.join(storageDir, 'telegram-bot-state.json');
  let offset = 0, stopped = false;
  let adminChatId = process.env.ADMIN_CHAT_ID ? String(process.env.ADMIN_CHAT_ID) : null;
  let receiptsEnabled = true, botEnabled = true, waitingForLink = null;
  const waitingForUserId = new Set(), waitingForSupport = new Set();
  const waitingForAdminReply = new Map(), waitingForUserReply = new Map();
  const pendingReceipts = new Map(), users = new Map(), supportTickets = new Map();
  const offlineQueue = [];
  const sleep = ms => new Promise(r => setTimeout(r, ms));
  const safe = s => String(s ?? '').replace(/[&<>]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));
  const displayName = u => [u?.first_name, u?.last_name].filter(Boolean).join(' ') || 'بدون نام';
  const displayUsername = u => u?.username ? `@${u.username}` : 'ندارد';
  const isAdmin = u => Boolean((adminChatId && String(u?.id) === adminChatId) || String(u?.username || '').toLowerCase() === ADMIN_USERNAME);

  function loadState() {
    try { if (!fs.existsSync(stateFile)) return; const s=JSON.parse(fs.readFileSync(stateFile,'utf8')); offset=Number(s.offset||0); adminChatId=s.adminChatId||adminChatId; receiptsEnabled=s.receiptsEnabled!==false; botEnabled=s.botEnabled!==false; waitingForLink=s.waitingForLink||null; for(const x of s.users||[])users.set(String(x.userId),x); for(const x of s.pendingReceipts||[])pendingReceipts.set(String(x.id),x); for(const x of s.supportTickets||[])supportTickets.set(String(x.id),x); } catch(e){console.error('[telegram] state load failed:',e.message);} }
  function saveState(){try{fs.mkdirSync(storageDir,{recursive:true});const data={offset,adminChatId,receiptsEnabled,botEnabled,waitingForLink,users:[...users.values()],pendingReceipts:[...pendingReceipts.values()],supportTickets:[...supportTickets.values()]};const tmp=`${stateFile}.tmp`;fs.writeFileSync(tmp,JSON.stringify(data,null,2));fs.renameSync(tmp,stateFile);}catch(e){console.error('[telegram] state save failed:',e.message);}}
  function telegram(method,body={}){return new Promise((resolve,reject)=>{const url=new URL(`${API}/${method}`),payload=JSON.stringify(body);const req=https.request({hostname:url.hostname,port:443,path:url.pathname,method:'POST',family:4,headers:{'content-type':'application/json','content-length':Buffer.byteLength(payload)},timeout:35000},res=>{let data='';res.setEncoding('utf8');res.on('data',c=>data+=c);res.on('end',()=>{try{const p=JSON.parse(data);if(!p.ok)return reject(new Error(p.description||`Telegram API error: ${method}`));resolve(p.result);}catch{reject(new Error(`Invalid Telegram response (${res.statusCode})`));}})});req.on('timeout',()=>req.destroy(new Error('Telegram request timed out')));req.on('error',reject);req.write(payload);req.end();});}
  const send=(chatId,text,extra={})=>telegram('sendMessage',{chat_id:chatId,text,parse_mode:'HTML',...extra});
  const sendPhoto=(chatId,photo,caption,extra={})=>telegram('sendPhoto',{chat_id:chatId,photo,caption,parse_mode:'HTML',...extra});
  const sendDocument=(chatId,document,caption,extra={})=>telegram('sendDocument',{chat_id:chatId,document,caption,parse_mode:'HTML',...extra});
  const copyMessage=(chatId,fromChatId,messageId,extra={})=>telegram('copyMessage',{chat_id:chatId,from_chat_id:fromChatId,message_id:messageId,...extra});
  const edit=(chatId,messageId,text,reply_markup)=>telegram('editMessageText',{chat_id:chatId,message_id:messageId,text,parse_mode:'HTML',reply_markup});

  const mainKeyboard=()=>({inline_keyboard:[[{text:'🎓 معرفی دوره',callback_data:'course'}],[{text:'📚 سرفصل‌ها',callback_data:'syllabus'},{text:'🎁 نمونه رایگان',callback_data:'sample'}],[{text:'💰 خرید دوره',callback_data:'buy'}],[{text:'💬 پشتیبانی',callback_data:'support'}]]});
  const back=()=>({inline_keyboard:[[{text:'↩️ برگشت به منوی اصلی',callback_data:'menu'}]]});
  // Clean, separate admin pages.
  const adminHome=()=>({inline_keyboard:[[{text:'🧾 مدیریت رسیدها',callback_data:'admin_receipts'}],[{text:'💬 مدیریت پشتیبانی',callback_data:'admin_support'}],[{text:'👥 مدیریت کاربران',callback_data:'admin_users'}],[{text:'⚙️ تنظیمات بات',callback_data:'admin_settings'}],[{text:'📊 آمار و وضعیت',callback_data:'admin_stats'}],[{text:'🆔 اطلاعات مدیر',callback_data:'admin_owner'}]]});
  const adminBack=()=>({inline_keyboard:[[{text:'↩️ پنل اصلی',callback_data:'admin_home'}]]});
  const adminReceipts=()=>({inline_keyboard:[[{text:'📥 رسیدهای جدید',callback_data:'pending_receipts'}],[{text:receiptsEnabled?'🟢 دریافت رسید: روشن':'🔴 دریافت رسید: خاموش',callback_data:'toggle_receipts'}],[{text:'↩️ پنل اصلی',callback_data:'admin_home'}]]});
  const adminSupport=()=>({inline_keyboard:[[{text:'📨 تیکت‌های باز',callback_data:'support_list'}],[{text:'↩️ پنل اصلی',callback_data:'admin_home'}]]});
  const adminUsers=()=>({inline_keyboard:[[{text:'🔎 جستجوی کاربر با ID',callback_data:'user_lookup'}],[{text:'↩️ پنل اصلی',callback_data:'admin_home'}]]});
  const adminSettings=()=>({inline_keyboard:[[{text:botEnabled?'🟢 بات: روشن':'🔴 بات: خاموش',callback_data:'toggle_bot'}],[{text:'📥 وضعیت صف اختلال',callback_data:'queue_status'}],[{text:'↩️ پنل اصلی',callback_data:'admin_home'}]]});
  const adminStats=()=>({inline_keyboard:[[{text:'🔄 بروزرسانی',callback_data:'admin_stats'}],[{text:'↩️ پنل اصلی',callback_data:'admin_home'}]]});
  const userKeyboard=id=>({inline_keyboard:[[{text:'👤 اطلاعات کاربر',callback_data:`user_info:${id}`}],[{text:'🟢 اعطای دسترسی',callback_data:`grant:${id}`},{text:'🔴 لغو دسترسی',callback_data:`revoke:${id}`}],[{text:'📥 رسیدهای کاربر',callback_data:`user_receipts:${id}`}],[{text:'🔗 ارسال دسترسی',callback_data:`user_link:${id}`}],[{text:'↩️ مدیریت کاربران',callback_data:'admin_users'}]]});
  const receiptKeyboard=id=>({inline_keyboard:[[{text:'👤 اطلاعات کاربر',callback_data:`info:${id}`}],[{text:'✅ تایید رسید',callback_data:`approve:${id}`},{text:'❌ رد رسید',callback_data:`reject:${id}`}],[{text:'🔗 ارسال لینک',callback_data:`link:${id}`}],[{text:'↩️ رسیدها',callback_data:'admin_receipts'}]]});
  const supportAdminKeyboard=id=>({inline_keyboard:[[{text:'↩️ پاسخ به این پیام',callback_data:`support_reply:${id}`}],[{text:'💬 پشتیبانی',callback_data:'admin_support'}]]});
  const supportUserKeyboard=id=>({inline_keyboard:[[{text:'↩️ پاسخ به همین پیام',callback_data:`support_user_reply:${id}`}],[{text:'🏠 منوی اصلی',callback_data:'menu'}]]});

  function getOrCreateUser(m){const id=String(m.from?.id||m.chat.id);let u=users.get(id);if(!u)u={userId:id,chatId:String(m.chat.id),name:displayName(m.from),username:m.from?.username||'',access:false,approved:false,rejected:false,createdAt:new Date().toISOString()};else{u.chatId=String(m.chat.id);u.name=displayName(m.from);u.username=m.from?.username||u.username||'';}users.set(id,u);saveState();return u;}
  function receiptParts(id){const m=String(id||'').match(/^(-?\d+):(\d+)$/);return m?{chatId:m[1],messageId:Number(m[2])}:null;}
  function getReceipt(id){const e=pendingReceipts.get(String(id));if(e)return e;const p=receiptParts(id);if(!p)return null;const r={id:String(id),chatId:p.chatId,userId:p.chatId,name:'کاربر رسید',username:'',approved:false,rejected:false,access:false,linkSent:'',fileType:'',fileId:''};pendingReceipts.set(String(id),r);users.set(String(r.userId),r);saveState();return r;}
  function messageSummary(m){if(m.text)return safe(m.text);if(m.caption)return safe(m.caption);if(m.photo)return '🖼️ عکس';if(m.video)return '🎥 ویدیو';if(m.document)return '📎 فایل';if(m.voice)return '🎤 پیام صوتی';if(m.audio)return '🎵 صوت';if(m.sticker)return '🙂 استیکر';return '📨 پیام';}
  function newTicketId(userId){return `${userId}-${Date.now()}`;}
  async function deliverSupportAdmin(ticket,m,reply=false){if(!adminChatId)return;const text=`<b>${reply?'🔁 پاسخ جدید کاربر':'💬 پیام جدید پشتیبانی'}</b>\n\n👤 ${safe(displayName(m.from))}\n🔹 ${safe(displayUsername(m.from))}\n🆔 Telegram ID: <code>${safe(ticket.userId)}</code>\n🎫 Ticket: <code>${safe(ticket.id)}</code>\n\n${messageSummary(m)}\n\n<i>این پیام متعلق به همین تیکت است.</i>`;const extra={reply_markup:supportAdminKeyboard(ticket.id)};if(m.photo)return sendPhoto(adminChatId,m.photo[m.photo.length-1].file_id,text,extra);if(m.document)return sendDocument(adminChatId,m.document.file_id,text,extra);if(m.video||m.voice||m.audio||m.sticker)return copyMessage(adminChatId,m.chat.id,m.message_id,extra);return send(adminChatId,text,extra);}
  async function createSupportTicket(m,idValue=null,reply=false){const u=getOrCreateUser(m);let t=idValue?supportTickets.get(String(idValue)):null;if(!t)t={id:newTicketId(u.userId),userId:u.userId,chatId:String(m.chat.id),name:u.name,username:u.username,status:'open',createdAt:new Date().toISOString(),lastUserMessageId:m.message_id,lastAdminMessageId:null,lastMessageSummary:messageSummary(m)};else{t.status='open';t.lastUserMessageId=m.message_id;t.lastMessageSummary=messageSummary(m);t.name=u.name;t.username=u.username;}supportTickets.set(t.id,t);saveState();await deliverSupportAdmin(t,m,reply);return t;}
  async function sendAdminReply(t,m){const u=users.get(String(t.userId)),chatId=t.chatId||u?.chatId||t.userId,extra={reply_markup:supportUserKeyboard(t.id)},cap=`<b>👑 پاسخ پشتیبانی</b>\n\n🎫 تیکت: <code>${safe(t.id)}</code>`;if(m.photo)await sendPhoto(chatId,m.photo[m.photo.length-1].file_id,cap,extra);else if(m.document)await sendDocument(chatId,m.document.file_id,cap,extra);else if(m.video||m.voice||m.audio||m.sticker)await copyMessage(chatId,m.chat.id,m.message_id,extra);else await send(chatId,`${cap}\n\n${safe(m.text||m.caption||'پیام جدید از پشتیبانی')}`,extra);t.lastAdminMessageId=m.message_id;t.lastAdminSummary=m.text||m.caption||'پیام پشتیبانی';t.status='waiting_user';saveState();}
  async function sendSupportList(chatId){const list=[...supportTickets.values()].filter(t=>t.status!=='closed');if(!list.length)return send(chatId,'📭 هیچ تیکت بازی وجود ندارد.',{reply_markup:adminSupport()});await send(chatId,`<b>💬 تیکت‌های باز</b>\n\nتعداد: <b>${list.length}</b>`,{reply_markup:adminSupport()});for(const t of list)await send(chatId,`<b>🎫 ${safe(t.id)}</b>\n👤 ${safe(t.name)}\n🔹 ${safe(t.username?'@'+t.username:'ندارد')}\n🆔 <code>${safe(t.userId)}</code>\n📌 ${t.status==='waiting_user'?'🟡 منتظر کاربر':'🟢 پیام جدید'}\n\nآخرین پیام: ${safe(t.lastMessageSummary||'')}`,{reply_markup:supportAdminKeyboard(t.id)});}
  async function sendPending(chatId){const list=[...pendingReceipts.values()].filter(r=>!r.approved&&!r.rejected);if(!list.length)return send(chatId,'📭 هیچ رسید تاییدنشده‌ای وجود ندارد.',{reply_markup:adminReceipts()});await send(chatId,`<b>📥 رسیدهای جدید</b>\n\nتعداد: <b>${list.length}</b>`,{reply_markup:adminReceipts()});for(const r of list){const text=`<b>📄 رسید پرداخت</b>\n\n🎓 ${safe(COURSE_TITLE)}\n💰 ${safe(COURSE_PRICE)}\n👤 ${safe(r.name)}\n🔹 ${safe(r.username?'@'+r.username:'ندارد')}\n🆔 <code>${safe(r.userId)}</code>`;const extra={reply_markup:receiptKeyboard(r.id)};if(r.fileType==='photo'&&r.fileId)await sendPhoto(chatId,r.fileId,text,extra);else if(r.fileType==='document'&&r.fileId)await sendDocument(chatId,r.fileId,text,extra);else await send(chatId,text,extra);}}
  async function showUser(chatId,id){const u=users.get(String(id));if(!u)return send(chatId,'⚠️ کاربر پیدا نشد.',{reply_markup:adminUsers()});return send(chatId,`<b>👤 مدیریت کاربر</b>\n\nنام: ${safe(u.name)}\nیوزرنیم: ${safe(u.username?'@'+u.username:'ندارد')}\n🆔 Telegram ID: <code>${safe(u.userId)}</code>\n💳 دسترسی: ${u.access?'🟢 دارد':'🔴 ندارد'}\n🧾 پرداخت: ${u.approved?'✅ تایید':'❌ تایید نشده'}`,{reply_markup:userKeyboard(u.userId)});}
  async function processOffline(){if(!botEnabled||!offlineQueue.length)return;const q=offlineQueue.splice(0);for(const x of q){try{if(x.type==='message'&&!x.admin){await send(x.chatId,'⚠️ به دلیل اختلال موقت، درخواست شما با تأخیر پردازش شد. بات دوباره فعال شده و درخواست شما در حال پردازش است.');await handleMessage(x.message,true);}else if(x.type==='callback')await handleCallback(x.callback,true);}catch(e){console.error('[telegram] queued:',e.message);}}}

  async function handleMessage(m,queued=false){const chatId=m.chat.id,text=String(m.text||'').trim(),admin=isAdmin(m.from);if(!botEnabled&&!admin&&!queued){offlineQueue.push({type:'message',chatId:String(chatId),message:m,admin:false});return;}if(admin){adminChatId=String(chatId);if(waitingForLink){const u=users.get(String(waitingForLink))||getReceipt(waitingForLink);if(!u){waitingForLink=null;saveState();return send(chatId,'⚠️ کاربر پیدا نشد.',{reply_markup:adminHome()});}if(!u.approved)return send(chatId,'⚠️ اول رسید را تایید کنید.',{reply_markup:adminHome()});try{await copyMessage(u.chatId,chatId,m.message_id);u.access=true;u.linkSent=text||'[پیام ارسال‌شده]';waitingForLink=null;saveState();return send(chatId,'✅ پیام برای کاربر ارسال شد و دسترسی فعال شد.',{reply_markup:adminHome()});}catch(e){return send(chatId,'❌ ارسال انجام نشد: '+safe(e.message),{reply_markup:adminHome()});}}if(waitingForAdminReply.has(String(chatId))){const id=waitingForAdminReply.get(String(chatId));waitingForAdminReply.delete(String(chatId));const t=supportTickets.get(id);if(!t)return send(chatId,'⚠️ تیکت پیدا نشد.',{reply_markup:adminSupport()});try{await sendAdminReply(t,m);return send(chatId,'✅ پاسخ برای کاربر ارسال شد.',{reply_markup:adminSupport()});}catch(e){return send(chatId,'❌ ارسال پاسخ ناموفق بود: '+safe(e.message),{reply_markup:adminSupport()});}}if(waitingForUserId.has(String(chatId))&&/^\d+$/.test(text)){waitingForUserId.delete(String(chatId));return showUser(chatId,text);}}
    if(text==='/start'||text==='/menu')return send(chatId,`<b>🎓 ${safe(COURSE_TITLE)}</b>\n\nآموزش کاربردی ساخت و مدیریت استوری اینستاگرام.\n\n💰 ${safe(COURSE_PRICE)}\n\nاز منوی زیر انتخاب کنید 👇`,{reply_markup:mainKeyboard()});
    if(text==='/id')return send(chatId,`🆔 Telegram ID شما:\n<code>${safe(chatId)}</code>`);
    if(text==='/admin')return admin?send(chatId,'<b>👑 پنل مدیریت</b>\n\nیک بخش را انتخاب کنید 👇',{reply_markup:adminHome()}):send(chatId,'⛔ این دستور فقط برای مدیر است.');
    if(waitingForUserReply.has(String(chatId))){const id=waitingForUserReply.get(String(chatId));waitingForUserReply.delete(String(chatId));const t=supportTickets.get(id);if(!t)return send(chatId,'⚠️ تیکت پیدا نشد.',{reply_markup:mainKeyboard()});await createSupportTicket(m,id,true);return send(chatId,`✅ پیام شما برای پشتیبانی ارسال شد.\n\n🎫 تیکت: <code>${safe(id)}</code>\n↩️ این پیام پاسخ به آخرین پیام مدیر است.`,{reply_markup:supportUserKeyboard(id)});}
    if(waitingForSupport.has(String(chatId))){waitingForSupport.delete(String(chatId));const t=await createSupportTicket(m);return send(chatId,`✅ پیام با موفقیت ارسال شد.\n\n🎫 شماره تیکت: <code>${safe(t.id)}</code>\n\nمنتظر پاسخ مدیران باشید.`,{reply_markup:back()});}
    if(m.photo||m.document){if(!receiptsEnabled)return send(chatId,'🔴 دریافت رسید فعلاً خاموش است.',{reply_markup:mainKeyboard()});if(!adminChatId)return send(chatId,'📤 رسید دریافت شد؛ مدیر هنوز بات را برای دریافت رسید تنظیم نکرده است.',{reply_markup:mainKeyboard()});const id=`${chatId}:${m.message_id}`,u=getOrCreateUser(m),r={...u,id,chatId:String(chatId),userId:String(m.from?.id||chatId),fileType:m.photo?'photo':'document',fileId:m.photo?m.photo[m.photo.length-1].file_id:m.document?.file_id||'',approved:false,rejected:false,access:false};pendingReceipts.set(id,r);users.set(r.userId,r);saveState();const cap=`<b>📥 رسید پرداخت جدید</b>\n\n🎓 ${safe(COURSE_TITLE)}\n💰 ${safe(COURSE_PRICE)}\n👤 ${safe(u.name)}\n🔹 ${safe(u.username?'@'+u.username:'ندارد')}\n🆔 <code>${safe(u.userId)}</code>`,extra={reply_markup:receiptKeyboard(id)};if(m.photo)await sendPhoto(adminChatId,r.fileId,cap,extra);else await sendDocument(adminChatId,r.fileId,cap,extra);return send(chatId,'📤 رسید دریافت شد و برای مدیر ارسال شد.',{reply_markup:mainKeyboard()});}
    return send(chatId,'از منوی زیر یک گزینه را انتخاب کنید 👇',{reply_markup:mainKeyboard()});}

  async function handleCallback(q,queued=false){const chatId=q.message.chat.id,action=String(q.data||'');try{await telegram('answerCallbackQuery',{callback_query_id:q.id});}catch{}if(!botEnabled&&!isAdmin(q.from)&&!queued){offlineQueue.push({type:'callback',callback:q});return;}
    if(action==='course')return edit(chatId,q.message.message_id,`<b>🎓 معرفی دوره</b>\n\nدوره <b>${safe(COURSE_TITLE)}</b> برای آموزش ساخت، ایده‌پردازی و مدیریت استوری‌های حرفه‌ای اینستاگرام.\n\n💰 ${safe(COURSE_PRICE)}`,back());
    if(action==='syllabus')return edit(chatId,q.message.message_id,'<b>📚 سرفصل‌ها</b>\n\n1️⃣ اصول طراحی استوری\n2️⃣ ایده‌پردازی و سناریونویسی\n3️⃣ ساخت استوری جذاب\n4️⃣ افزایش تعامل\n5️⃣ فروش و برندینگ',back());
    if(action==='sample')return edit(chatId,q.message.message_id,'<b>🎁 نمونه رایگان</b>\n\nنمونه رایگان دوره در این بخش قرار می‌گیرد.',back());
    if(action==='buy')return edit(chatId,q.message.message_id,`<b>💳 خرید دوره</b>\n\n🎓 ${safe(COURSE_TITLE)}\n💰 ${safe(COURSE_PRICE)}\n\nبعد از پرداخت، رسید را از گزینه زیر ارسال کنید.`,{inline_keyboard:[...(PAYMENT_URL?[[{text:'💳 پرداخت',url:PAYMENT_URL}]]:[]),[{text:'📤 ارسال رسید',callback_data:'send_receipt'}],[{text:'↩️ برگشت',callback_data:'menu'}]]});
    if(action==='send_receipt')return edit(chatId,q.message.message_id,`<b>📤 ارسال رسید</b>\n\nتصویر یا فایل رسید پرداخت را همینجا ارسال کنید.\n\n💰 ${safe(COURSE_PRICE)}`,back());
    if(action==='support'){waitingForSupport.add(String(chatId));return edit(chatId,q.message.message_id,'<b>💬 پشتیبانی</b>\n\nپیامی که می‌خواهید به پشتیبانی بگویید را ارسال کنید.\n\nمتن، عکس، فایل، ویدیو یا پیام صوتی قابل ارسال است.',back());}
    if(action==='menu')return send(chatId,'<b>🏠 منوی اصلی</b>\n\nیک گزینه را انتخاب کنید 👇',{reply_markup:mainKeyboard()});
    if(action.startsWith('support_user_reply:')){const id=action.slice('support_user_reply:'.length);if(!supportTickets.has(id))return send(chatId,'⚠️ تیکت پیدا نشد.',{reply_markup:mainKeyboard()});waitingForUserReply.set(String(chatId),id);return send(chatId,`<b>↩️ پاسخ به پشتیبانی</b>\n\n🎫 تیکت: <code>${safe(id)}</code>\n\nپیام خود را ارسال کنید تا برای مدیر ارسال شود.`,{reply_markup:back()});}
    if(!isAdmin(q.from))return send(chatId,'⛔ این بخش فقط برای مدیر است.');adminChatId=String(chatId);saveState();
    if(action==='admin_home')return send(chatId,'<b>👑 پنل مدیریت</b>\n\nیک بخش را انتخاب کنید 👇',{reply_markup:adminHome()});
    if(action==='admin_receipts')return send(chatId,'<b>🧾 مدیریت رسیدها</b>\n\nرسیدهای پرداخت را از اینجا بررسی کنید.',{reply_markup:adminReceipts()});
    if(action==='admin_support')return send(chatId,'<b>💬 مدیریت پشتیبانی</b>\n\nتیکت‌ها و پیام‌های کاربران را از اینجا مدیریت کنید.',{reply_markup:adminSupport()});
    if(action==='admin_users')return send(chatId,'<b>👥 مدیریت کاربران</b>\n\nبرای مدیریت یک کاربر، Telegram ID او را جستجو کنید.',{reply_markup:adminUsers()});
    if(action==='admin_settings')return send(chatId,'<b>⚙️ تنظیمات بات</b>\n\nتنظیمات عملکرد بات را از این بخش کنترل کنید.',{reply_markup:adminSettings()});
    if(action==='admin_stats')return send(chatId,`<b>📊 آمار و وضعیت</b>\n\n👥 کاربران: <b>${users.size}</b>\n🧾 رسیدهای باز: <b>${[...pendingReceipts.values()].filter(r=>!r.approved&&!r.rejected).length}</b>\n💬 تیکت‌های باز: <b>${[...supportTickets.values()].filter(t=>t.status!=='closed').length}</b>\n📥 صف اختلال: <b>${offlineQueue.length}</b>\n\n🤖 بات: ${botEnabled?'🟢 روشن':'🔴 خاموش'}\n🧾 رسید: ${receiptsEnabled?'🟢 روشن':'🔴 خاموش'}`,{reply_markup:adminStats()});
    if(action==='admin_owner')return send(chatId,`<b>🆔 اطلاعات مدیر</b>\n\nUsername: @${safe(ADMIN_USERNAME)}\nChat ID: <code>${safe(chatId)}</code>`,{reply_markup:adminBack()});
    if(action==='pending_receipts')return sendPending(chatId);
    if(action==='support_list')return sendSupportList(chatId);
    if(action==='user_lookup'){waitingForUserId.add(String(chatId));return send(chatId,'🆔 Telegram ID کاربر را ارسال کنید:',{reply_markup:adminBack()});}
    if(action==='queue_status')return send(chatId,`<b>📥 صف اختلال</b>\n\nتعداد درخواست‌های ذخیره‌شده: <b>${offlineQueue.length}</b>`,{reply_markup:adminSettings()});
    if(action==='toggle_receipts'){receiptsEnabled=!receiptsEnabled;saveState();return send(chatId,receiptsEnabled?'🟢 دریافت رسید روشن شد.':'🔴 دریافت رسید خاموش شد.',{reply_markup:adminReceipts()});}
    if(action==='toggle_bot'){botEnabled=!botEnabled;saveState();if(botEnabled){await send(chatId,'🟢 بات فعال شد؛ درخواست‌های ذخیره‌شده پردازش می‌شوند.',{reply_markup:adminSettings()});await processOffline();return;}return send(chatId,'🔴 بات خاموش شد؛ درخواست‌های کاربران ذخیره می‌شوند.',{reply_markup:adminSettings()});}
    const [cmd,...parts]=action.split(':'),value=parts.join(':');
    if(cmd==='support_reply'){if(!supportTickets.has(value))return send(chatId,'⚠️ تیکت پیدا نشد.',{reply_markup:adminSupport()});waitingForAdminReply.set(String(chatId),value);return send(chatId,`<b>↩️ پاسخ به تیکت</b>\n\n🎫 <code>${safe(value)}</code>\n\nپیام پاسخ را ارسال کنید. هر نوع پیام قابل ارسال است.`,{reply_markup:adminSupport()});}
    if(cmd==='info'){const r=getReceipt(value);if(!r)return send(chatId,'⚠️ رسید پیدا نشد.',{reply_markup:adminReceipts()});return send(chatId,`<b>👤 اطلاعات کاربر</b>\n\nنام: ${safe(r.name)}\nیوزرنیم: ${safe(r.username?'@'+r.username:'ندارد')}\n🆔 <code>${safe(r.userId)}</code>\nرسید: ${r.approved?'✅ تایید':r.rejected?'❌ رد':'⏳ در انتظار'}\nدسترسی: ${r.access?'🟢 دارد':'🔴 ندارد'}`,{reply_markup:receiptKeyboard(value)});}
    if(cmd==='approve'){const r=getReceipt(value);if(!r)return send(chatId,'⚠️ رسید پیدا نشد.',{reply_markup:adminReceipts()});r.approved=true;r.rejected=false;r.access=false;saveState();try{await send(r.chatId,`<b>✅ رسید شما تایید شد.</b>\n\n🎓 ${safe(COURSE_TITLE)}\n\nمدیر آماده ارسال دسترسی است.`);}catch{}return send(chatId,'✅ رسید تایید شد. برای ارسال دسترسی «🔗 ارسال لینک» را بزنید.',{reply_markup:receiptKeyboard(value)});}
    if(cmd==='reject'){const r=getReceipt(value);if(!r)return send(chatId,'⚠️ رسید پیدا نشد.',{reply_markup:adminReceipts()});r.rejected=true;r.approved=false;r.access=false;saveState();try{await send(r.chatId,'❌ رسید پرداخت شما رد شد. در صورت اشتباه، رسید صحیح را دوباره ارسال کنید.');}catch{}return send(chatId,'❌ رسید رد شد.',{reply_markup:adminReceipts()});}
    if(cmd==='link'){const r=getReceipt(value);if(!r)return send(chatId,'⚠️ رسید پیدا نشد.',{reply_markup:adminReceipts()});if(!r.approved)return send(chatId,'⚠️ اول رسید را تایید کنید.',{reply_markup:adminReceipts()});waitingForLink=String(r.userId);saveState();return send(chatId,`📨 پیام بعدی شما دقیقاً برای کاربر <code>${safe(r.userId)}</code> ارسال می‌شود.`,{reply_markup:adminReceipts()});}
    if(cmd==='user_info')return showUser(chatId,value);
    if(cmd==='grant'){const u=users.get(String(value));if(!u)return send(chatId,'⚠️ کاربر پیدا نشد.',{reply_markup:adminUsers()});u.access=true;saveState();return send(chatId,'🟢 دسترسی فعال شد.',{reply_markup:userKeyboard(value)});}
    if(cmd==='revoke'){const u=users.get(String(value));if(!u)return send(chatId,'⚠️ کاربر پیدا نشد.',{reply_markup:adminUsers()});u.access=false;saveState();return send(chatId,'🔴 دسترسی لغو شد.',{reply_markup:userKeyboard(value)});}
    if(cmd==='user_receipts'){const list=[...pendingReceipts.values()].filter(r=>r.userId===String(value));if(!list.length)return send(chatId,'📭 رسیدی برای این کاربر ثبت نشده است.',{reply_markup:userKeyboard(value)});for(const r of list)await send(chatId,`🎫 رسید <code>${safe(r.id)}</code>\nوضعیت: ${r.approved?'✅ تایید':r.rejected?'❌ رد':'⏳ در انتظار'}`,{reply_markup:receiptKeyboard(r.id)});return;}
    if(cmd==='user_link'){const u=users.get(String(value));if(!u)return send(chatId,'⚠️ کاربر پیدا نشد.',{reply_markup:adminUsers()});if(!u.approved)return send(chatId,'⚠️ اول رسید کاربر را تایید کنید.',{reply_markup:adminUsers()});waitingForLink=String(value);saveState();return send(chatId,`📨 پیام بعدی شما برای کاربر <code>${safe(value)}</code> ارسال می‌شود.`,{reply_markup:adminUsers()});}
    return send(chatId,'<b>👑 پنل مدیریت</b>',{reply_markup:adminHome()});
  }

  async function poll(){while(!stopped){try{const updates=await telegram('getUpdates',{offset,timeout:25,allowed_updates:['message','callback_query']});for(const u of updates){offset=u.update_id+1;saveState();try{if(u.callback_query)await handleCallback(u.callback_query);else if(u.message)await handleMessage(u.message);}catch(e){console.error('[telegram] update error:',e.message);}}}catch(e){console.error('[telegram] polling error:',e.message);await sleep(3000);}}}
  async function startup(){loadState();try{await telegram('deleteWebhook',{drop_pending_updates:false});}catch(e){console.error('[telegram] deleteWebhook:',e.message);}try{const me=await telegram('getMe');console.log(`[telegram] bot connected: @${me.username||me.first_name}`);}catch(e){console.error('[telegram] getMe failed:',e.message);}await sleep(1500);if(botEnabled)await processOffline();poll();}
  process.once('SIGTERM',()=>{stopped=true;saveState();});process.once('SIGINT',()=>{stopped=true;saveState();});startup();module.exports={telegram};
}
